name: Deploy pythonChat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v2
      - name: Crear Entorno Virtual
        run: |
          python3 -m venv venv
      - name: Activar Entorno Virtual
        run: |
          source venv/bin/activate
      - name: Instalar Dependencias
        run: |
          pip install -r requirements.txt
      - name: Crear archivo config.py
        run: |
          echo "IP = '${{ secrets.IP }}'" > config.py
          echo "PORT = '${{ secrets.PORT }}'" >> config.py
          echo "SQLALCHEMY_DATABASE_URI = '${{ secrets.SQLALCHEMY_DATABASE_URI }}'" >> config.py
