name: Deploy pythonChat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v3
      - name: Crear y activar entorno virtual, instalar dependencias
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Crear archivo config.py
        run: |
          echo "IP = '${{ secrets.IP }}'" > config.py
          echo "PORT = ${{ secrets.PORT }}" >> config.py
          echo "SQLALCHEMY_DATABASE_URI = '${{ secrets.SQLALCHEMY_DATABASE_URI }}'" >> config.py
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Establecer flag para el reinicio del servicio
        run: touch /home/joboufra/actions-pythonChat/deploy/ok