name: Deploy pythonChat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Restart app
      run: |
        sudo systemctl restart app
