name: Deploy Flask App - pythonChat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2

    - name: Copiar al servidor
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "."
        target: "/path/to/your/app"

    - name: Reiniciar servicio
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /path/to/your/app
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart pythonChat
